# -*- coding: utf-8 -*-
"""Follium_Map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VRk-VJKtRi8yzphBhpjtVV3fia7pc4ax
"""

pip install folium

import folium

m= folium.Map(location = [-28.4792625, 24.6727135] , tile = 'Stamen Toner', zoom_start = [6])
#create city markers and add them to map object
folium.Marker(location=[-26.204103, 28.047304],popup='Johannesburg:\n 2026000',icon=folium.Icon(color ='green')).add_to(m)
folium.Marker(location=[-29.858681, 31.021839],popup='Durban:\n 3120000',icon=folium.Icon(color='red')).add_to(m)
folium.Marker(location=[ -33.918861, 18.423300],popup='Cape Town \n: 3433000',icon=folium.Icon(color='blue')).add_to(m)
folium.Marker(location=[-26.248537, 27.854033],popup='Soweto:\n 1695000',icon=folium.Icon(color = 'pink')).add_to(m)
folium.Marker(location=[-25.747868, 28.229271],popup='Pretoria:\n 1691000',icon=folium.Icon(color='orange')).add_to(m)
m
#m.save('index.html')